name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: 118.178.231.120
        SERVER_USER: root
        SERVER_PATH: /var/www/kennenchat/
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf $SERVER_PATH/build"
        scp -r ./build $SERVER_USER@$SERVER_HOST:$SERVER_PATH
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          cd $SERVER_PATH/build && 
          npm install -g serve && 
          nohup serve -s build &
        "
